<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_a-dynamic-image sl-sobe-carousel-sub-card-img</name>
   <tag></tag>
   <elementGuidId>8938204f-3f8c-4445-b4f7-a4d18c0685ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sobe_d_b_5_3']/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sobe_d_b_5_3 > a.sl-sobe-carousel-sub-card-link > div.sl-sobe-carousel-sub-card-image > img.a-dynamic-image.sl-sobe-carousel-sub-card-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>26471704-d097-4481-afe6-8fb8dc1794dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Headphones</value>
      <webElementGuid>5bf58f2b-b0f9-4359-91bb-312a56ca7d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/31/img23/CEPC/BAU/ELP/navtiles/Headphones._CB574550011_.png</value>
      <webElementGuid>f0fe6f18-2ad4-49d4-830a-41210ccd9275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dynamic-image sl-sobe-carousel-sub-card-img</value>
      <webElementGuid>5066bf87-1f54-4b73-a51f-583f5401593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dynamic-image</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>234cb772-7db5-4c00-b2cc-22c9ec428b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sobe_d_b_5_3&quot;)/a[@class=&quot;sl-sobe-carousel-sub-card-link&quot;]/div[@class=&quot;sl-sobe-carousel-sub-card-image&quot;]/img[@class=&quot;a-dynamic-image sl-sobe-carousel-sub-card-img&quot;]</value>
      <webElementGuid>4dd5c741-188f-41aa-92c5-75a67cd20cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sobe_d_b_5_3']/a/div/img</value>
      <webElementGuid>24633ecd-37aa-420f-b427-9beeb4707d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Headphones']</value>
      <webElementGuid>2bb1473b-0e43-43d6-a3e7-ff3a95240313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/section/div/div/div/div/div/ol/li[3]/a/div/img</value>
      <webElementGuid>c1893d64-47a5-460e-8dbf-ba68cefaae3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Headphones' and @src = 'https://m.media-amazon.com/images/G/31/img23/CEPC/BAU/ELP/navtiles/Headphones._CB574550011_.png']</value>
      <webElementGuid>a350a6f9-9d49-4e46-bb4b-de8f7c9e3bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
