<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>69d315c1-1828-46e7-b0a6-add9c0c13bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._1yQHx8._2UnIQ_._3ak8Rd._2y8Yzt > div > div.css-1dbjc4n.r-14lw9ot.r-13awgt0.r-eqz5dr > div > div > div._3n8fnaug._3n8fnamv._3n8fnaf9._3n8fna1._3n8fna7n._1i2djtb9._1i2djt0 > div > div.css-1dbjc4n > div._3MlEpv > div.tLbyDf > div._25HC_u > div.css-1dbjc4n.r-13awgt0 > div > div > a._3n8fnaug._3n8fnars._3n8fnak6._3n8fna4y._3n8fnack._1i2djtb9._1i2djtf > div.zlQd20._1eDlvI > img[alt=&quot;Image&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>73a93b77-6d30-42ff-b44d-3363b7b9fa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-assets-web.flixcart.com/www/linchpin/batman-returns/images/fk-default-image-75ff340b.png?q=90</value>
      <webElementGuid>42e22f54-d5b8-4feb-9e7b-95460d49fbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>78baca7f-9b4a-4108-8e88-99859c94516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image</value>
      <webElementGuid>903b6123-5159-426c-b0e6-539521d52b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;yAlKeh&quot;]/div[@class=&quot;_2L0uxW&quot;]/div[@class=&quot;_3116_u&quot;]/div[@class=&quot;_1yQHx8 _2UnIQ_ _3ak8Rd _2y8Yzt&quot;]/div[1]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-13awgt0 r-eqz5dr&quot;]/div[1]/div[1]/div[@class=&quot;_3n8fnaug _3n8fnamv _3n8fnaf9 _3n8fna1 _3n8fna7n _1i2djtb9 _1i2djt0&quot;]/div[1]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;_3MlEpv&quot;]/div[@class=&quot;tLbyDf&quot;]/div[@class=&quot;_25HC_u&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[1]/div[1]/a[@class=&quot;_3n8fnaug _3n8fnars _3n8fnak6 _3n8fna4y _3n8fnack _1i2djtb9 _1i2djtf&quot;]/div[@class=&quot;zlQd20 _1eDlvI&quot;]/img[1]</value>
      <webElementGuid>52937341-4e84-46ad-b785-f172e6c0592c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>09964f95-7067-4d97-a033-acaf9e9a10e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Image'])[34]</value>
      <webElementGuid>6d19366c-93a4-4617-9ad1-2ff849dbe14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>dfdf6385-28f0-4ed3-a400-e7c268224e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static-assets-web.flixcart.com/www/linchpin/batman-returns/images/fk-default-image-75ff340b.png?q=90' and @alt = 'Image']</value>
      <webElementGuid>5074b5c7-a7d5-46d4-afd6-3f1fb6743518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
