<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nav-sprite hmenu-close-icon</name>
   <tag></tag>
   <elementGuidId>8ba1debd-3573-457d-a387-f5595126c57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-canvas-background']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav-sprite.hmenu-close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af7f8d10-16c7-4422-bf67-f168f6cb064c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sprite hmenu-close-icon</value>
      <webElementGuid>1a5bed6b-bae8-45f4-80bb-02f6eb55ac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-canvas-background&quot;)/div[@class=&quot;nav-sprite hmenu-close-icon&quot;]</value>
      <webElementGuid>b98822be-8c25-4998-8da8-223450b236ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-canvas-background']/div</value>
      <webElementGuid>128cbf4b-59f1-4427-a70f-17c67ad9e241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>9fe0e219-5d51-4d3e-8591-4aeecdecb966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
