<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_a-dynamic-image sl-sobe-carousel-sub-card-img</name>
   <tag></tag>
   <elementGuidId>f28858b2-a79d-401a-ba67-56061b9c21e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sobe_d_b_7_2 > a.sl-sobe-carousel-sub-card-link > div.sl-sobe-carousel-sub-card-image > img.a-dynamic-image.sl-sobe-carousel-sub-card-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sobe_d_b_7_2']/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>621a139b-3da2-4333-be96-e57bc188adee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Shop now</value>
      <webElementGuid>811d6121-ec24-4186-8d3f-381dad0893c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/31/img23/Wireless/nbshagun/CLP/BSK/Feb1/02._CB583557388_.jpg</value>
      <webElementGuid>c0f77e29-6ea8-496a-a675-7071d5cfba45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dynamic-image sl-sobe-carousel-sub-card-img</value>
      <webElementGuid>5d700dae-3871-4f9a-8228-d33ceb9f8dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dynamic-image</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>8b652d38-88bf-40b2-adcc-da2318ad327e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sobe_d_b_7_2&quot;)/a[@class=&quot;sl-sobe-carousel-sub-card-link&quot;]/div[@class=&quot;sl-sobe-carousel-sub-card-image&quot;]/img[@class=&quot;a-dynamic-image sl-sobe-carousel-sub-card-img&quot;]</value>
      <webElementGuid>bd34094e-92a5-40a9-93b7-2ba56d5172fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sobe_d_b_7_2']/a/div/img</value>
      <webElementGuid>3a0152b9-a096-4d66-aacd-40ce6acaa99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Shop now'])[2]</value>
      <webElementGuid>1612e429-65c1-409c-bd26-850d7b37792c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ol/li[2]/a/div/img</value>
      <webElementGuid>3dd4ab5c-d86c-4add-8346-fb845c935938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Shop now' and @src = 'https://m.media-amazon.com/images/G/31/img23/Wireless/nbshagun/CLP/BSK/Feb1/02._CB583557388_.jpg']</value>
      <webElementGuid>6ea8d22e-d31d-4d18-8a5f-8dc42f24cb1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
